### ISSUE TITLE
🚀 [feature] 디자이너 견적서 작성, 구매자 결제

### ISSUE THREAD

**Issue by YJKBigBo** [jjsOrganization/client#18]
# 🤖 기능 개요
디자이너의 견적서 작성 및 구매자 결제 로직 구현

## ✅ Todo
- [x] 구현 내용 1. 채팅내용을 바탕으로 디자이너가 견적서를 작성
- [x] 구현 내용 2. 견적서 작성 및 채팅 종료
- [x] 구현 내용 3. 구매자의 견적서 승인 및 결제, 배송정보 입력
