### ISSUE TITLE
🚀 [feature] 마이페이지 채팅 구현

### ISSUE THREAD

**Issue by YJKBigBo** [jjsOrganization/client#4]
# 🤖 기능 개요

## ✅ Todo
- [x] 구현 내용 1. 구매자 마이페이지 리폼을 위한 채팅 구현
- [x] 구현 내용 2. 디자이너 마이페이지 리폼을 위한 채팅 구현
- [x] 구현 내용 3. 채팅을 바탕으로 견적서 구현
