### ISSUE TITLE
🚀 [feature] 물 시각화 or 차트화

### ISSUE THREAD

**Issue by YJKBigBo** [jjsOrganization/client#45]
# 🤖 기능 개요
절약된 물에 대한 데이터를 시각화 하여 사용자에게 보여줌으로써 얼마만큼 물을 아꼈는지 확인가능하게 함

## ✅ Todo
- [x] 구현 내용 1. 절약된 물에 대한 정보를 시각화 함
- [x] 구현 내용 2. 애니메이션화
- [x] 구현 내용 3. 차트화
